[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "asgiref>=3.8.1",
  "dnspython>=2.7.0",
  "eve>=2.2.0",
  "eve-swagger>=0.2.0",
  "flask-jwt-extended[asymmetric-crypto]>=4.7.1",
  "httpx>=0.28.1",
  "python-dotenv>=1.0.1",
  "python-jose[cryptography]>=3.4.0",
  "uvicorn>=0.34.0",
]

[tool.ruff]
select = ["E", "F", "I"]
ignore = ["E501"]
indent-width = 2
